### ISSUE TITLE
Singularity Hub

### ISSUE THREAD

**Issue by vsoch** [tikk3r/lofar-grid-hpccloud#18]
hey @tikk3r - over the last (8 hours?) you've requested your container `tikk3r/lofar-grid-hpccloud:lofar` over 70 times - I want to give you a heads up that the weekly GET limit for any container is 100, so you only have about 25 more to go before your request will be denied. I'd suggest for your usage or testing that you use a strategy that will pull a container first, put it in a shared or cached location, and then interact with the binary directly. More details are [here](https://singularityhub.github.io/singularityhub-docs/2019/release-announcement/), and let me know if you have any questions.

**Comment by tikk3r** [comment]
This should now be fixed. Containers are stored on a shared location and only pulled when updated or if a run can't find it from the shared location.

**Comment by vsoch** [comment]
Thanks @tikk3r it's greatly appreciated!
