### ISSUE TITLE
Add h5py and aplpy (Python 2.7)

### ISSUE THREAD

**Issue by mooneyse** [tikk3r/lofar-grid-hpccloud#19]
The LOFAR [long-baseline pipeline relies on this](https://github.com/lmorabit/long_baseline_pipeline/blob/288aca4c389db74020153d32969fa70a089ed17d/bin/loop3B_v1.py#L20). Thank you.

**Comment by mooneyse** [comment]
Note: This is for the loop 3 script, but aplpy is also required.

**Comment by tikk3r** [comment]
Aplpy has been added, forgot h5py, which will be in there soon.

**Comment by mooneyse** [comment]
Thanks a million :clap:
