### ISSUE TITLE
shub pullissue

### ISSUE THREAD

**Issue by alexmatze** [tikk3r/lofar-grid-hpccloud#25]
Today I encountered an issue, when trying to pull the latest version from shub via:

singularity pull --name lofar.simg shub://tikk3r/lofar-grid-hpccloud:lofar

I get the following error msg:
ERROR Cannot find image. Is your capitalization correct?

**Comment by tikk3r** [comment]
That image does not exist (anymore). There's only `lofar_sksp` and `lofar_base`.

**Comment by alexmatze** [comment]
I see, thanks! Maybe the git-info should reflect that
