### ISSUE TITLE
Intel Singularity build crashes at sharedarray

### ISSUE THREAD

**Issue by AlexKurek** [tikk3r/lofar-grid-hpccloud#56]
Just reporting:

```
Building wheel for sharedarray (setup.py): started
  Building wheel for sharedarray (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
```

Full log:
[singularity.zip](https://github.com/tikk3r/flocs/files/11241466/singularity.zip)

**Comment by tikk3r** [comment]
Thanks for reporting this. I ran into this myself the other day and looking into it.
