### ISSUE TITLE
wcslib issue from Dockerfile

### ISSUE THREAD

**Issue by HannoSpreeuw** [tikk3r/lofar-grid-hpccloud#6]
```docker build -t try-lofar-grid-hpccloud .```
spends considerable time building, but crashes on
"
.......
-- Installing: /opt/lofar/cfitsio/include/fitsio.h
-- Installing: /opt/lofar/cfitsio/include/longnam.h
Removing intermediate container 20a658dd0e5e
 ---> e89e11e4d429
Step 54/157 : RUN mkdir ${INSTALLDIR}/wcslib
 ---> Running in 34d43e911bc8
Removing intermediate container 34d43e911bc8
 ---> c11e6f361f33
Step 55/157 : RUN if [ "${WCSLIB_VERSION}" = "latest" ]; then cd ${INSTALLDIR}/wcslib && wget --retry-connrefused ftp://anonymous@ftp.atnf.csiro.au/pub/software/wcslib/wcslib.tar.bz2 -O wcslib-latest.tar.bz2; fi
 ---> Running in 225566014c64
Removing intermediate container 225566014c64
 ---> 1b5b2cd96574
Step 56/157 : RUN if [ "${WCSLIB_VERSION}" != "latest" ]; then cd ${INSTALLDIR}/wcslib && wget --retry-connrefused ftp://anonymous@ftp.atnf.csiro.au/pub/software/wcslib/wcslib-${WCSLIB_VERSION}.tar.bz2; fi
 ---> Running in f4c9de8cc341
--2018-11-08 09:24:40--  ftp://anonymous@ftp.atnf.csiro.au/pub/software/wcslib/wcslib-5.16.tar.bz2
           => 'wcslib-5.16.tar.bz2'
Resolving ftp.atnf.csiro.au (ftp.atnf.csiro.au)... 150.229.106.20
Connecting to ftp.atnf.csiro.au (ftp.atnf.csiro.au)|150.229.106.20|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/software/wcslib ... done.
==> SIZE wcslib-5.16.tar.bz2 ... done.
==> PASV ... done.    ==> RETR wcslib-5.16.tar.bz2 ... 
No such file 'wcslib-5.16.tar.bz2'.

The command '/bin/sh -c if [ "${WCSLIB_VERSION}" != "latest" ]; then cd ${INSTALLDIR}/wcslib && wget --retry-connrefused ftp://anonymous@ftp.atnf.csiro.au/pub/software/wcslib/wcslib-${WCSLIB_VERSION}.tar.bz2; fi' returned a non-zero code: 8
"

**Comment by HannoSpreeuw** [comment]
![image](https://user-images.githubusercontent.com/11661087/48189899-86dfe680-e341-11e8-9a43-eb02c4686716.png)
This explains it. The 5.16 is no longer there.

**Comment by HannoSpreeuw** [comment]
So I set
 ```ENV WCSLIB_VERSION 5.20```
but that produced some other error:
"
.........
flex  -t fitshdr.l | sed -e 's/^[	 ]*#/#/' > fitshdr.c

flex  -t wcsbth.l | sed -e 's/^[	 ]*#/#/' > wcsbth.c

flex  -t wcsulex.l | sed -e 's/^[	 ]*#/#/' > wcsulex.c

Building WCSLIB C library...
make: invalid option -- 'O'
make: invalid option -- 'a'
make: invalid option -- 'g'
Usage: make [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.
  -C DIRECTORY, --directory=DIRECTORY
                              Change to DIRECTORY before doing anything.
  -d                          Print lots of debugging information.
  --debug[=FLAGS]             Print various types of debugging information.
  -e, --environment-overrides
.......
"

**Comment by tikk3r** [comment]
Ah yes, I haven't updated the Docker image in a while since we no not/cannot run that here. WCSLIB has the nasty habit of removing older versions once they release new ones.
CentOS ships with an outdated `make`, which causes all the invalid options you see. Can you run Singularity images? I'll try to update the Dockerfile to reflect the current Singularity ones. https://github.com/tikk3r/lofar-grid-hpccloud/blob/master/Singularity_ubuntu_kern is much more up-to-date, if you can run Singularity images that is.

**Comment by HannoSpreeuw** [comment]
Same issue with building a Singularity image:
`sudo singularity build centos.simg Singularity`
gives 

> Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/software/wcslib ... done.
==> SIZE wcslib-5.18.tar.bz2 ... done.
==> PASV ... done.    ==> RETR wcslib-5.18.tar.bz2 ... 
No such file 'wcslib-5.18.tar.bz2'.

ABORT: Aborting with RETVAL=255
Cleaning up...

**Comment by HannoSpreeuw** [comment]
`export WCSLIB_VERSION=5.20.` again gives a different error:

>  Building WCSLIB C library...
make: invalid option -- 'O'
make: invalid option -- 'a'
make: invalid option -- 'g'
Usage: make [options] [target] ...

**Comment by HannoSpreeuw** [comment]
Singularity_ubuntu_kern builds flawlessly.

**Comment by tikk3r** [comment]
Kern is by far the easiest to setup, the others allow more finetuned control of version, but at a risk as you see. Thanks for reporting these issues. I'll update / clean up the other recipes soon.

**Comment by tikk3r** [comment]
Closing this as there is no plan for now to go back to Dockers soon.
