### ISSUE TITLE
Minimal working example

### ISSUE THREAD

**Issue by HannoSpreeuw** [tikk3r/lofar-grid-hpccloud#7]
A working example of a running Singularity container would be nice.
I.e. the parsets and a pipeline.cfg.
And a link to the data.
Or perhaps upload a small Measurement Set to e.g. ftp://ftp.astron.nl/outgoing.

**Comment by tikk3r** [comment]
I've been expanding the wiki a little bit: https://github.com/tikk3r/lofar-grid-hpccloud/wiki/Using-an-image

**Comment by HannoSpreeuw** [comment]
Nice. I copied the directions for KERN images wrt pipeline.cfg. Are there also KERN specific directions for the parsets?
I ran into

>   $LOFARROOT/bin/makesourcedb is an invalid value for ExecField executable

**Comment by tikk3r** [comment]
I think changing the `$LOFARROOT` in the parset to `input.output.lofarroot` might fix that. The variable `$LOFARROOT` is not defined in the image. I'm going on a whim here, but since they can set `job_directory` this way, maybe it works for this too.

**Comment by HannoSpreeuw** [comment]
That did make a difference. Now I am running into

> 2018-12-07 16:28:38 INFO    genericpipeline.executable_args: recipe executable_args completed
2018-12-07 16:28:38 INFO    genericpipeline: Beginning step h5_imp_cal_map
2018-12-07 16:28:38 INFO    genericpipeline: Beginning step h5imp_cal
2018-12-07 16:28:38 INFO    genericpipeline: Running task: executable_args
2018-12-07 16:28:38 ERROR   genericpipeline: *******************************************
2018-12-07 16:28:38 ERROR   genericpipeline: Failed pipeline run: Pre-Facet-Calibrator
2018-12-07 16:28:38 ERROR   genericpipeline: Detailed exception information:
2018-12-07 16:28:38 ERROR   genericpipeline: <type 'exceptions.TypeError'>
2018-12-07 16:28:38 ERROR   genericpipeline: /opt/lofar/losoto/bin/losoto/bin/H5parm_collector.py is an invalid value for ExecField executable

**Comment by tikk3r** [comment]
Could be an error in the parset at that specific step. Check the `losoto_directory` variable and the `h5imp_cal` step and see if they match/are sensible.

**Comment by HannoSpreeuw** [comment]
I have
`! losoto_directory         =  /opt/lofar/losoto/bin/losoto` as recommended on the wiki.

`h5imp_cal.control.executable                         =   {{ losoto_directory }}/bin/H5parm_collector.py`
is default.

However, as mentioned, that results in a rather unusual path with a ```bin````directory inside a ```bin````directory:
```2018-12-07 16:28:38 ERROR genericpipeline: /opt/lofar/losoto/bin/losoto/bin/H5parm_collector.py is an invalid value for ExecField executable```

**Comment by tikk3r** [comment]
Ah yeah. The executable should end up being pointed to `/opt/lofar/losoto/bin/losoto`, so the `losoto_directory` should be just `/opt/lofar/losoto`.

**Comment by HannoSpreeuw** [comment]
The error persists:

>  2018-12-10 15:11:17 INFO    genericpipeline: Beginning step h5imp_cal
2018-12-10 15:11:17 INFO    genericpipeline: Running task: executable_args
/usr/lib/python2.7/dist-packages/lofarpipe/support/subprocessgroup.pyc : Using default subprocess module!
2018-12-10 15:11:17 ERROR   genericpipeline: *******************************************
2018-12-10 15:11:17 ERROR   genericpipeline: Failed pipeline run: Pre-Facet-Calibrator
2018-12-10 15:11:17 ERROR   genericpipeline: Detailed exception information:
2018-12-10 15:11:17 ERROR   genericpipeline: <type 'exceptions.TypeError'>
2018-12-10 15:11:17 ERROR   genericpipeline: /opt/lofar/losoto/bin/H5parm_collector.py is an invalid value for ExecField executable

**Comment by tikk3r** [comment]
Does it exist in the image? You can check with `singularity shell <image>` and then `ls /opt/lofar/losoto`.

**Comment by HannoSpreeuw** [comment]
Apparently not:
`[hspreeuw@fs5 Singularity]$ singularity shell writable_ubuntu_kern.simg`
> Singularity:
 Invoking an interactive shell within container...

Singularity writable_ubuntu_kern.simg:~/Containers/Singularity> ls /opt/lofar/losoto

> ls:

 cannot access '/opt/lofar/losoto': No such file or directory

**Comment by HannoSpreeuw** [comment]
This an Ubuntu Kern image.

**Comment by tikk3r** [comment]
I checked the recipe. It's probably in `/opt/losoto`. If not there, then it's probably in the standard location somewhere in `/usr/lib64/site-packages/losoto` or something.

**Comment by HannoSpreeuw** [comment]
`/opt/losoto` indeed.

**Comment by HannoSpreeuw** [comment]
That was with two subbands, but strangely enough this error persists with 244 subbands.

**Comment by HannoSpreeuw** [comment]
Fixed this by removing the statefile. Now running into:

>  INFO: --> Starting 'clock_smooth' step (operation: SMOOTH).
INFO: Smoothing soltab: clock000
/usr/local/lib/python2.7/dist-packages/numpy/lib/function_base.py:3250: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)
INFO: Writing results...
INFO: Step 'clock_smooth' completed successfully.
INFO: Time for this step: 0 s (cpu: 0 s).
INFO: --> Starting 'bandpass' step (operation: PREFACTOR_BANDPASS).
INFO: Running prefactor_bandpass on: amplitude000
INFO: Have 307.0 subbands.
INFO: Removing user-specified subband: 307
INFO: Removing user-specified subband: 308
INFO: Creating a new solution-table: bandpass.
INFO: Step 'bandpass' completed successfully.
INFO: Time for this step: 6 s (cpu: 6 s).
INFO: --> Starting 'xyoffset' step (operation: PREFACTOR_XYOFFSET).
INFO: Running XYoffset on: phase000
Traceback (most recent call last):
  File "/opt/losoto/bin/losoto", line 4, in <module>
    __import__('pkg_resources').run_script('losoto==2.0', 'losoto')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "/opt/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/EGG-INFO/scripts/losoto", line 145, in <module>
    returncode += ops[ op ]._run_parser( soltab, parser, step )
  File "/opt/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/losoto/operations/prefactor_XYoffset.py", line 14, in _run_parser
    return run(soltab, chanWidth)
  File "/opt/losoto/lib/python2.7/site-packages/losoto-2.0-py2.7.egg/losoto/operations/prefactor_XYoffset.py", line 73, in run
    offsetHz = subbandHz / 2.0 - 0.5 * chanWidthHz
TypeError: can't multiply sequence by non-int of type 'float'

**Comment by tikk3r** [comment]
Could be something with the solutions, the data or maybe losoto I guess. One of `subbandHz` or `chanWidthHz` seems to be a list, which may need to be a numpy array. The losoto repository may be a better place to ask.

**Comment by HannoSpreeuw** [comment]
Perhaps I need to apply [the script](http://www.astron.nl/radio-observatory/observing-capabilities/depth-technical-information/system-notes/wrong-information-) first. 
But that seems unrelated.

**Comment by HannoSpreeuw** [comment]
I posted [this issue](https://github.com/revoltek/losoto/issues/78#issue-393547628) at the Losoto repo.

**Comment by HannoSpreeuw** [comment]
[According to this comment](https://github.com/revoltek/losoto/issues/78#issuecomment-453955565) we should build the Singularity container using prefactor 3.0.

**Comment by HannoSpreeuw** [comment]
SInce prefactor consists of parsets for the genericpipeline and genericpipeline is part of the Lofar Software Package, this basically means using lofar 3.0 or later.

**Comment by tikk3r** [comment]
That should all be good. Prefactor is not put in the image (deliberately, as it changes so often at the moment), and it is built with LOFAR 3.2.2 as it is in the master branch now. I have successfully run a prefactor 3.0 calibrator run with a Singularity image.
This was with one built from https://github.com/tikk3r/lofar-grid-hpccloud/tree/stagebuild (this will eventually become master, as it makes certain things easier), but the master branch should work as well I think.

**Comment by HannoSpreeuw** [comment]
Same error from the Singularity.lofar image from the stagebuild branch.

**Comment by HannoSpreeuw** [comment]
After [this Losoto bug fix](https://github.com/revoltek/losoto/commit/df76329beecfb1b7a555095e9ea809258b667893) I got my desired minimal working example.
