### ISSUE TITLE
Unrecognized argument

### ISSUE THREAD

**Issue by vijaymahatma** [tikk3r/lofar-grid-hpccloud#75]
I'm running the delay-calibration using the flocs runner script, using the following command:

`./run_lofar-vlbi-delay-calibration.sh -s /beegfs/general/mahatmav/lofar/long_baseline/pipeline/flocs_v5.0.0_sandybridge_sandybridge_mkl_cuda.sif -b /beegfs -l /beegfs/general/mahatmav/lofar/long_baseline/pipeline/LINC -r /beegfs/general/mahatmav/lofar/long_baseline/4C29_41/ -d /beegfs/general/mahatmav/lofar/long_baseline/4C29_41/L695399/ -v /beegfs/general/mahatmav/lofar/long_baseline/pipeline/VLBI-cwl/ -c /beegfs/general/mahatmav/lofar/long_baseline/4C29_41/L695399_LINC_target/results_LINC_target/cal_solutions.h5`

This runs for a few seconds until hitting this error:

`create_ms_list.py: error: unrecognized arguments: --facetselfcal=/beegfs/general/mahatmav/lofar/long_baseline/4C29_41/tmp.sBrXnBqwqC/lofar_facet_selfcal
VLBI-cwl starting
WARNING - software has been build with -march=sandybridge but current machine reports -march=znver2.
If you encounter strange behaviour or Illegal instruction warnings, consider building a container with the appropriate architecture set.
WARNING - software has been build with -mtune=sandybridge but current machine -mtune=znver2.
If you encounter strange behaviour or Illegal instruction warnings, consider building a container with the appropriate architecture set.
INFO /opt/lofar/pyenv-py3/bin/cwltool 3.1.20240112164112
INFO Resolved '/beegfs/general/mahatmav/lofar/long_baseline/pipeline/VLBI-cwl/workflows/delay-calibration.cwl' to 'file:///beegfs/general/mahatmav/lofar/long_baseline/pipeline/VLBI-cwl/workflows/delay-calibration.cwl'
ERROR Tool definition failed validation:
[Errno 2] No such file or directory: '/beegfs/general/mahatmav/lofar/long_baseline/4C29_41/tmp.sBrXnBqwqC/mslist_VLBI_delay_calibration.json'

real    0m1.515s
user    0m0.441s
sys     0m0.944s
VLBI-cwl ended`

I noticed that create_ms_list and the run_lofar-vlbi-delay-calibration.sh have inconsistent arguments for calling facetselfcal (the runner scipt calls "--facetselfcal " while create_ms_list.py calls "--selfcal" -- I manually changed them to make them consistent but this led to exactly the same error, so it's probably something else.

**Comment by tikk3r** [comment]
This has been fixed a few weeks ago, but after the release of the container so the one that ships inside the container is indeed broken. I recommend trying the latest one from the repository instead of using the one included in the container until the next container release.

> I noticed that create_ms_list and the run_lofar-vlbi-delay-calibration.sh have inconsistent arguments for calling facetselfcal (the runner scipt calls "--facetselfcal " while create_ms_list.py calls "--selfcal" -- I manually changed them to make them consistent but this led to exactly the same error, so it's probably something else.

The location of facetselfal is specified through `selfcal` for the [delay calibration workflow](https://git.astron.nl/RD/VLBI-cwl/-/blob/master/workflows/delay-calibration.cwl?ref_type=heads#L62). I updated `create_ms_list.py` to map one-to-one with the workflows it generates, but I do agree this parameter is confusing.

**Comment by vijaymahatma** [comment]
Do you mean just downloading the latest version of runners and re-running?

**Comment by tikk3r** [comment]
> Do you mean just downloading the latest version of runners and re-running?

Yep. The latest runner should have it fixed.

**Comment by vijaymahatma** [comment]
Cheers, it's doing something now.
