### ISSUE TITLE
TGSSphase or TGSSphase_final

### ISSUE THREAD

**Issue by jurjen93** [tikk3r/lofar-grid-hpccloud#76]
I have noticed that some of the LINC target runs return TGSSphase_final instead of TGSSphase as solution table name (not entirely sure why). Would it be an idea to update `--phasesol` within the script if `--solset` is given (you can read the table names from the solsets)? So, if the name is TGSSphase_final, the default of `--phasesol` changes to TGSSphase_final, otherwise leave TGSSphase.
This would help to avoid crashes for automatic approaches or avoiding the need of making work arounds to update the json output.

**Comment by tikk3r** [comment]
That is due to the selfcal. The final `cal_solutions.h5` should contain both TGSSphase with the solutions from the TGSS solve and TGSSphase_final with the solutions of the selfcal solve. Nonetheless, such a check could be added.

**Comment by jurjen93** [comment]
Ah yes, selfcal ofc.

![image](https://github.com/tikk3r/flocs/assets/18346230/e73e68a9-31b2-4f21-a8bb-a2e3697c2130)
There are no TGSSphase solutions for me though (see screenshot). This happens for all observations where the additional selfcal has been run for.

**Comment by shulevski** [comment]
This also causes the VLBI delay calibration pipeline to fail if using the runner and not giving the `-e --phasesol=TGSSphase_final` option at runtime (which users should not need to know).

**Comment by tikk3r** [comment]
I've started a possible fix on the [auto-check-tgssphase](https://github.com/tikk3r/flocs/tree/auto-check-tgssphase) branch. The `--phasesol` option should accept an `auto` value, in which case it will try one of the default names.

**Comment by tikk3r** [comment]
Resolved with #82
