### ISSUE TITLE
How to set up log4cplus appenders for the Singularity container?

### ISSUE THREAD

**Issue by HannoSpreeuw** [tikk3r/lofar-grid-hpccloud#9]
I issued
`singularity exec -B /path/to/data/ ubuntu_kern.simg genericpipeline.py  -d -c pipeline.cfg Pre-Facet-Calibrator.parset`
and ran into 

> log4cplus:ERROR No appenders could be found for logger (LCS.Common.EXCEPTION).
log4cplus:ERROR Please initialize the log4cplus system properly.

It is unclear to me how to setup the log4cplus appenders.
`module load log4cplus` does not suffice.

**Comment by tikk3r** [comment]
I have seen this "error" for as long as I have been using the software. I don't even compile it with log4cplus anymore and just turn it off. It can be safely ignored.

**Comment by HannoSpreeuw** [comment]
Thanks
