### ISSUE TITLE
Default IONEX Server change

### ISSUE THREAD

**Issue by shulevski** [tikk3r/lofar-grid-hpccloud#92]
Several months ago the LINC code was changed and the default server to get the needed ionospheric state files is now: `ftp://gssc.esa.int/gnss/products/ionex/` with the prefix `UQRG`. The create_ms_list.py script should reflect this change, otherwise if a user runs the LINC pipeline specifying the old default, it may error out in target runs at the RMExtract step for data taken in the last 1-2 years...

See: [https://git.astron.nl/RD/LINC/-/issues/52](https://git.astron.nl/RD/LINC/-/issues/52)

**Comment by tikk3r** [comment]
Thanks for reporting. Does that default work for every observation or do we need a switch for younger than 1-2 years ago and older than that?

**Comment by shulevski** [comment]
I think they should work for all data sets. Hopefully the LINC developers know what they are doing ;) Most likely the old server stopped and the new one contains info on previous years as well.

**Comment by tikk3r** [comment]
Updated with #93 .
