### ISSUE TITLE
building-containers.html says gcc 11, changelog says CASAcore 3.6.1

### ISSUE THREAD

**Issue by AlexKurek** [tikk3r/lofar-grid-hpccloud#99]
**Describe the bug**
Just reporting a small issue: at the very bottom of https://tikk3r.github.io/flocs/docs/building-containers.html it says gcc 11, but in fact it is gcc 13 (Fedora 38). These docs are not avaliable to edit on github (?), so Im unable to make a PR.
Also [changelog](https://github.com/tikk3r/flocs/releases/tag/v5.3.0) says CASAcore 3.6.1, while if facts it seems to be 3.5.0.

**Comment by tikk3r** [comment]
Fixed.
